# Business Cycles R Workflow
#
# Purpose:
# Create economist-grade statistical summaries and a phase-based regression
# using the quarterly panel generated by the Python pipeline.

library(readr)
library(dplyr)
library(ggplot2)
library(broom)
library(sandwich)
library(lmtest)
library(zoo)

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("--file=", args, value = TRUE)

if (length(file_arg) > 0) {
  script_path <- normalizePath(sub("--file=", "", file_arg[1]))
  base_dir <- normalizePath(file.path(dirname(script_path), ".."))
} else {
  base_dir <- normalizePath(getwd())
}

panel_path <- file.path(base_dir, "data", "processed", "business_cycles_quarterly_panel.csv")
table_dir <- file.path(base_dir, "outputs", "tables")
figure_dir <- file.path(base_dir, "outputs", "figures")

dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

panel <- read_csv(panel_path, show_col_types = FALSE) |>
  mutate(
    date = as.Date(date),
    recession = recession_indicator == 1,
    phase = factor(business_cycle_phase)
  )

phase_summary <- panel |>
  group_by(phase) |>
  summarise(
    observations = n(),
    avg_real_gdp_growth_annualized = mean(real_gdp_growth_annualized, na.rm = TRUE),
    avg_unemployment_rate = mean(unemployment_rate, na.rm = TRUE),
    avg_output_gap_pct = mean(output_gap_pct, na.rm = TRUE),
    avg_payroll_growth_yoy_pct = mean(payroll_growth_yoy_pct, na.rm = TRUE),
    avg_industrial_production_yoy_pct = mean(industrial_production_yoy_pct, na.rm = TRUE),
    avg_retail_sales_yoy_pct = mean(retail_sales_yoy_pct, na.rm = TRUE),
    avg_real_income_yoy_pct = mean(real_income_yoy_pct, na.rm = TRUE),
    avg_federal_funds_rate = mean(federal_funds_rate, na.rm = TRUE),
    .groups = "drop"
  )

write_csv(phase_summary, file.path(table_dir, "business_cycle_r_phase_summary.csv"))

model_df <- panel |>
  select(real_gdp_growth_annualized, delta_unemployment_rate, output_gap_pct, recession_indicator, federal_funds_rate) |>
  filter(
    !is.na(real_gdp_growth_annualized),
    !is.na(delta_unemployment_rate),
    !is.na(output_gap_pct),
    !is.na(federal_funds_rate)
  )

cycle_model <- lm(
  real_gdp_growth_annualized ~ delta_unemployment_rate + output_gap_pct + recession_indicator + federal_funds_rate,
  data = model_df
)

cycle_robust <- coeftest(cycle_model, vcov = vcovHC(cycle_model, type = "HC1"))
cycle_results <- tidy(cycle_robust)
write_csv(cycle_results, file.path(table_dir, "business_cycle_r_results.csv"))

phase_plot <- ggplot(panel, aes(x = output_gap_pct, y = unemployment_rate, color = phase)) +
  geom_point(alpha = 0.65) +
  labs(
    title = "Business-Cycle Phases: Output Gap and Unemployment",
    subtitle = "Recession and expansion quarters occupy different regions of macroeconomic stress.",
    x = "Output gap (%)",
    y = "Unemployment rate (%)",
    color = "Phase"
  ) +
  theme_minimal()

ggsave(
  filename = file.path(figure_dir, "business_cycle_phase_scatter_r.png"),
  plot = phase_plot,
  width = 8,
  height = 5,
  dpi = 300
)

print(phase_summary)
print(cycle_results)
