# Economic Resilience R Workflow
#
# Purpose:
# Create economist-grade statistical summaries and an Okun-style regression
# using the quarterly panel generated by the Python pipeline.

library(readr)
library(dplyr)
library(ggplot2)
library(broom)
library(sandwich)
library(lmtest)

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("--file=", args, value = TRUE)

if (length(file_arg) > 0) {
  script_path <- normalizePath(sub("--file=", "", file_arg[1]))
  base_dir <- normalizePath(file.path(dirname(script_path), ".."))
} else {
  base_dir <- normalizePath(getwd())
}

panel_path <- file.path(base_dir, "data", "processed", "economic_resilience_quarterly_panel.csv")
table_dir <- file.path(base_dir, "outputs", "tables")
figure_dir <- file.path(base_dir, "outputs", "figures")

dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

panel <- read_csv(panel_path, show_col_types = FALSE) |>
  mutate(
    date = as.Date(date),
    recession = recession_indicator == 1
  )

recession_summary <- panel |>
  filter(!is.na(unemployment_rate)) |>
  group_by(recession) |>
  summarise(
    observations = n(),
    avg_unemployment_rate = mean(unemployment_rate, na.rm = TRUE),
    avg_real_gdp_growth_annualized = mean(real_gdp_growth_annualized, na.rm = TRUE),
    avg_output_gap_pct = mean(output_gap_pct, na.rm = TRUE),
    avg_federal_funds_rate = mean(federal_funds_rate, na.rm = TRUE),
    .groups = "drop"
  )

write_csv(recession_summary, file.path(table_dir, "recession_summary_r.csv"))

okun_df <- panel |>
  select(date, real_gdp_growth_annualized, delta_unemployment_rate, recession_indicator, output_gap_pct) |>
  filter(
    !is.na(real_gdp_growth_annualized),
    !is.na(delta_unemployment_rate)
  )

okun_model <- lm(delta_unemployment_rate ~ real_gdp_growth_annualized, data = okun_df)
okun_robust <- coeftest(okun_model, vcov = vcovHC(okun_model, type = "HC1"))

okun_results <- tidy(okun_robust)
write_csv(okun_results, file.path(table_dir, "okun_r_results.csv"))

okun_plot <- ggplot(okun_df, aes(x = real_gdp_growth_annualized, y = delta_unemployment_rate)) +
  geom_point(alpha = 0.65) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.8) +
  geom_hline(yintercept = 0, linewidth = 0.3) +
  geom_vline(xintercept = 0, linewidth = 0.3) +
  labs(
    title = "Okun-Style Relationship in R",
    subtitle = "Quarterly real GDP growth and unemployment-rate changes",
    x = "Real GDP growth, annualized (%)",
    y = "Quarterly change in unemployment rate"
  ) +
  theme_minimal()

ggsave(
  filename = file.path(figure_dir, "okun_relationship_r.png"),
  plot = okun_plot,
  width = 8,
  height = 5,
  dpi = 300
)

print(recession_summary)
print(okun_results)
