# Stabilization Policy R Workflow
#
# Purpose:
# Create economist-grade statistical summaries and policy-response regressions
# using the quarterly panel generated by the Python pipeline.

library(readr)
library(dplyr)
library(ggplot2)
library(broom)
library(sandwich)
library(lmtest)
library(zoo)

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("--file=", args, value = TRUE)

if (length(file_arg) > 0) {
  script_path <- normalizePath(sub("--file=", "", file_arg[1]))
  base_dir <- normalizePath(file.path(dirname(script_path), ".."))
} else {
  base_dir <- normalizePath(getwd())
}

panel_path <- file.path(base_dir, "data", "processed", "stabilization_policy_quarterly_panel.csv")
table_dir <- file.path(base_dir, "outputs", "tables")
figure_dir <- file.path(base_dir, "outputs", "figures")

dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

panel <- read_csv(panel_path, show_col_types = FALSE) |>
  mutate(
    date = as.Date(date),
    recession = recession_indicator == 1,
    phase = factor(policy_phase)
  )

phase_summary <- panel |>
  group_by(phase) |>
  summarise(
    observations = n(),
    avg_real_gdp_growth_annualized = mean(real_gdp_growth_annualized, na.rm = TRUE),
    avg_unemployment_rate = mean(unemployment_rate, na.rm = TRUE),
    avg_output_gap_pct = mean(output_gap_pct, na.rm = TRUE),
    avg_cpi_inflation_yoy_pct = mean(cpi_inflation_yoy_pct, na.rm = TRUE),
    avg_federal_funds_rate = mean(federal_funds_rate, na.rm = TRUE),
    avg_gov_spending_growth_yoy_pct = mean(gov_spending_growth_yoy_pct, na.rm = TRUE),
    avg_policy_rate_gap = mean(policy_rate_gap, na.rm = TRUE),
    .groups = "drop"
  )

write_csv(phase_summary, file.path(table_dir, "stabilization_r_phase_summary.csv"))

model_df <- panel |>
  select(
    federal_funds_rate,
    cpi_inflation_yoy_pct,
    output_gap_pct,
    delta_unemployment_rate,
    recession_indicator,
    gov_spending_growth_yoy_pct
  ) |>
  filter(
    !is.na(federal_funds_rate),
    !is.na(cpi_inflation_yoy_pct),
    !is.na(output_gap_pct),
    !is.na(delta_unemployment_rate)
  )

policy_model <- lm(
  federal_funds_rate ~ cpi_inflation_yoy_pct + output_gap_pct +
    delta_unemployment_rate + recession_indicator,
  data = model_df
)

policy_robust <- coeftest(policy_model, vcov = vcovHC(policy_model, type = "HC1"))
policy_results <- tidy(policy_robust)
write_csv(policy_results, file.path(table_dir, "stabilization_r_results.csv"))

phase_plot <- ggplot(panel, aes(x = output_gap_pct, y = federal_funds_rate, color = phase)) +
  geom_point(alpha = 0.65) +
  labs(
    title = "Stabilization Policy: Output Gap and Policy Rate",
    subtitle = "Fiscal and monetary context differs across expansion and recession phases.",
    x = "Output gap (%)",
    y = "Federal funds rate (%)",
    color = "Phase"
  ) +
  theme_minimal()

ggsave(
  filename = file.path(figure_dir, "stabilization_phase_scatter_r.png"),
  plot = phase_plot,
  width = 8,
  height = 5,
  dpi = 300
)

print(phase_summary)
print(policy_results)
